permalink: /:year/:month/:day/:title.html
paginate: 6
paginate_path: "page:num"
markdown: kramdown
kramdown:
  input: GFM

# 作者信息
author: 
  name: 登登
  email: dengdeng1110@163.com
  github: http://github.com/dengkui

# 站点信息
title: 登登
description: My personal blog
url: http://dengkui.space
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/safe1.png
favicon: /public/img/safe1.png

# google analytics 设置
ga:
  id: UA-69951808-1 
  url: dengkui.space
  
#多说
comments :
     provider : duoshuo
     duoshuo : 
     short_name : dengkui

# 主题设置，自动激活某个标签
active: 阅读

# 首页除了最新文章外显示分类
#cates: 
# - 随感
#  - 可视化
#  - 模型学习

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
