permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: 登登
  email: dengdeng1110@163.com
  github: http://github.com/dengkui

# 站点信息
title: 登登的博客
description: My personal blog
url: http://dengkui.space
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/safe1.jpg
favicon: /public/img/safe1.jpg


# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - 诗词
  - 软件

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档